### ISSUE TITLE
Question: Why is this repo not in libsdl-org?

### ISSUE THREAD

**Issue by Croydon** [icculus/SDL_sound#18]
Why is this repository not in the libsdl-org?

**Comment by icculus** [comment]
It's not an official SDL project, just a personal one.

**Comment by Croydon** [comment]
Is the difference a matter of maintenance and support promises or are there a set of criteria that determine what can become an official project?

**Comment by icculus** [comment]
I just felt that creating a new library without warning didn't give me the right to impose it on another organization.
