### ISSUE TITLE
"release" tag

### ISSUE THREAD

**Issue by rofl0r** [icculus/SDL_sound#19]
hi there, since the last release goes back several years, and the commit hashes changed since the switch from hg, would you mind doing an occasional tag so distros have something specific they can point to to get a tarball ? it doesn't really matter whether it's a proper release, for example it'd be perfectly fine if current master is tagged as e.g. "v1.0.4-beta1".

**Comment by icculus** [comment]
We're wrapping up 2.0.0 right now, and I'll likely tag a 1.0.4 release at the same time, since it's still compatible with SDL 1.2.

**Comment by rathann** [comment]
Friendly reminder from Fedora packager.

**Comment by icculus** [comment]
@sezero Any last things you want to do before we call this an official 2.0.0 release? I resolved all the significant pending issues and fixed up a few other things.

**Comment by sezero** [comment]
Some of SDL_sound customizations are lost during dr_libs updates, i.e.
the dr??_xx typedefs:
https://github.com/icculus/SDL_sound/commit/7af16f9e8fe4c19b3914bbc64575786949120e89#diff-b2358ee18b313be4b84decbd86886f3d40507e5188b2a8e83be6f3b4445a3bceL70

Do we want them back or do we not care?

**Comment by icculus** [comment]
> Do we want them back or do we not care?

It was intentional, in hopes that we can just use dr_* unmodified on future upgrades. I think it'll be okay.

**Comment by sezero** [comment]
OK - I have nothing further

**Comment by sezero** [comment]
> OK - I have nothing further

Well, I lied - just pushed a style / warning cleanup patch to coreaudio.c

Nothing further now, I swear :)

**Comment by icculus** [comment]
Just realizing that timidity isn't public domain. I'm going to default that to disabled in the CMake file.

**Comment by sezero** [comment]
SDL_mixer has no problems with it?

**Comment by icculus** [comment]
SDL_mixer defaults to disabled, too:

https://github.com/libsdl-org/SDL_mixer/blob/main/CMakeLists.txt#L18

But also SDL_mixer cares less about this stuff than I do. For example, this is a non-starter for me in the Artistic License:

```
4. You may distribute the programs of this Package in object code or
executable form, provided that you do at least ONE of the following:

    a) distribute a Standard Version of the executables and library files,
    together with instructions (in the manual page or equivalent) on where
    to get the Standard Version.

    b) accompany the distribution with the machine-readable source of
    the Package with your modifications.

    c) give non-standard executables non-standard names, and clearly
    document the differences in manual pages (or equivalent), together
    with instructions on where to get the Standard Version.

    d) make other distribution arrangements with the Copyright Holder.
```

...for open source game development and for people that are careful about these things, it's not unreasonable, but SDL_mixer _should_ make it much more clear that you're getting other licensing requirements if you enable that.

**Comment by icculus** [comment]
...I wonder if I could just write a MIDI decoder really fast: https://www.personal.kent.edu/~sbirch/Music_Production/MP-II/MIDI/midi_file_format.htm

:)

**Comment by sezero** [comment]
> SDL_mixer defaults to disabled, too:
> 
> https://github.com/libsdl-org/SDL_mixer/blob/main/CMakeLists.txt#L18

The cmake'ry in SDL_mixer is mostly a placeholder, something to say that
"hey look, we have cmake support", but we actually don't: The relevant build
system in SDL_mixer is autotools and it has timidity enabled.

**Comment by rofl0r** [comment]
if a timidity is a no-starter due to license, maybe best to go back to modplug, it used to work quite well after sezero merged my patch (of course, having a clean implementation from scratch would be even better...)

**Comment by sezero** [comment]
> But also SDL_mixer cares less about this stuff than I do. For example, this is a non-starter for me in the Artistic License:

On that note, if you have a way of contacting Tuukka Toivonen (if he is
alive), maybe you can convince him to change the Artistic License option
to [Clarified Artistic License](https://spdx.org/licenses/ClArtistic.html) or to Zlib or something.

**Comment by sezero** [comment]
> if a timidity is a no-starter due to license, maybe best to go back to modplug,

Ewww..

**Comment by icculus** [comment]
Okay, I think we're going to go with what we have, but with Timidity disabled unless the user toggles it on. If I write a public domain replacement that doesn't suck, we'll drop Timidity, but that's not going to happen today.

I have some other things I'd like to rip up in the source code, but let's mark what we have as 2.0.1 (revision control has listed itself as 2.0.0 for _years_ so the bump is probably a good idea) and ship it.

**Comment by icculus** [comment]
> has listed itself as 2.0.0 for years 

(well, _year_, actually, but just in case someone was shipping this code...)

**Comment by icculus** [comment]
Okay, we're live!  https://github.com/icculus/SDL_sound/releases/tag/v2.0.1

I'm going to branch off a stable-2.0 branch from here for fixes. Big changes continue to go into main.

**Comment by sezero** [comment]
A little late, but noticed that the release tarball extracts as `SDL_sound-2.0.1` and _not_ as `SDL2_sound-2.0.1`: is this an oversight?

**Comment by sezero** [comment]
> A little late, but noticed that the release tarball extracts as `SDL_sound-2.0.1` and _not_ as `SDL2_sound-2.0.1`: is this an oversight?

Opened https://github.com/icculus/SDL_sound/issues/36 for it, so that it won't get lost.
