### ISSUE TITLE
ugrade to newer versions of dr_flac and dr_mp3

### ISSUE THREAD

**Issue by sezero** [icculus/SDL_sound#20]
dr_flac and dr_mp3 have received multitudes of updates since I last
touched them in Sep. 2018. I haven't upgraded to the newer versions
because I felt lazy about dealing with the api changes.

**Comment by icculus** [comment]
I'll take care of this once 2.0.16 is done.

**Comment by sezero** [comment]
As far ass I can tell though, it actually works OK as it is.

**Comment by icculus** [comment]
I think dr_mp3 added a seek API since then, but I might be misremembering. Upgrading these is a good idea in any case.

**Comment by icculus** [comment]
These are both updated now, as of a90d00123e474d217bab03c2903c40c8bbcf4ba6 for dr_flac and 7af16f9e8fe4c19b3914bbc64575786949120e89 for dr_mp3.
