### ISSUE TITLE
minimum required SDL2 version and SDL_exp()

### ISSUE THREAD

**Issue by sezero** [icculus/SDL_sound#21]
Without vorbis support, all builds and links fine, down to SDL2-2.0.4.
Vorbis however, requires SDL_exp() which was added in SDL2-2.0.9. Now:

- `exp()` won't ever be a few lines of fallback code to add.

- We can add `2.0.9` to `find_package(SDL2)` in CMakeLists.txt, however for
  that to work cmake needs to find `sdl2-config-version.cmake`, and it
  is only installed by SDL >= 2.0.12.

What to do about it?  Simply require 2.0.12 or newer, which might be a
bit too much?

**Comment by ericoporto** [comment]
Can't it fallback to use exp if there's no SDL_exp macro?

**Comment by sezero** [comment]
`SDL_exp` is not a macro, it's a function call. We can possibly detect its existence at configuration time. As for falling back to `exp`, maybe, @icculus to decide.
