### ISSUE TITLE
MSVC error: 'SDL_memmove': redefinition; different linkage

### ISSUE THREAD

**Issue by ericoporto** [icculus/SDL_sound#25]
Hi,

So I am having a weird error building with CMake MSVC 2015 and SDL 2.0.16 - the error doesn't happen with SDL 2.0.12.

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime_string.h(47): error C2375: 'SDL_memmove': redefinition; different linkage
```

The error is at link time and appears to be due to a warn I get on `SDL_sound_mp3.c`:

```
SDL_sound_mp3.c
     7>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime_string.h(47): error C2375: 'SDL_memmove': redefinition; different linkage [C:\Lib\SDL_sound\build\SDL2_sound-static.vcxproj]
         c:\lib\sdl2\include\SDL_stdinc.h(506): note: see declaration of 'SDL_memmove'
     7>C:\Lib\SDL_sound\src\SDL_sound_mp3.c(143): warning C4244: 'return': conversion from 'const drmp3_uint64' to 'Uint32', possible loss of data [C:\Lib\SDL_sound\build\SDL2_sound-static.vcxproj]
```

Looking this file, I see the line below

https://github.com/icculus/SDL_sound/blob/e921b5f39f9b4e84fda9d86119a6adab505fd210/src/SDL_sound_mp3.c#L44

It doesn't seem that neither `memmove` or `SDL_memmove` is used in SDL_sound_mp3. Is it necessary here?

**Comment by sezero** [comment]
memmove (and memcpy and memset)  are used in dr_mp3.h

One solution to this would be prefixing those three in dr_mp3.h with e.g. `drmp3_`
and changing the defines in SDL_sound_mp3.c accordingly. @icculus?

**Comment by sezero** [comment]
I went ahead and pushed https://github.com/icculus/SDL_sound/commit/b63aba4d605cf588aa8102b7febe21976bf459ba
If it works for you we can close this (and I'd submit the change to mainstream drmp3)

**Comment by ericoporto** [comment]
@sezero your commit fixed for me! Feel free to close this issue!
