### ISSUE TITLE
Question about building with MSVC

### ISSUE THREAD

**Issue by ericoporto** [icculus/SDL_sound#30]
Hi! I was looking at SDL_sound from the perspective from people used with Visual Studio, and noticed that the `SDL2-devel-2.0.X-VC.zip` packages in SDL don't ship a `sdl2-config.cmake` file, so someone that wants to build SDL_sound on Windows may have a hard time figuring how to satisfy the SDL2 dependency - they will also need to build SDL2 from source.

Which is a more desired path, include `sdl2-config.cmake` in SDL2 or add a vcxproj and solution files in this project?

**Comment by icculus** [comment]
I believe we have an open bug in SDL2 to add the cmake stuff.
