### ISSUE TITLE
`make install` missing

### ISSUE THREAD

**Issue by jengelh** [icculus/SDL_sound#33]
SDL_sound 2.0.1 has no `make install` action defined after cmake has run through the build, which is a step down from 1.0.3.

**Comment by sezero** [comment]
Can't reproduce this:  After configuring with cmake and building, I can
run `make install` and it, well, installs. You have to give us some more
details, I guess.

Just pushed https://github.com/icculus/SDL_sound/commit/ed1e4da5ce52282bdf16671a939b85c501b4bb95 to use GNUInstalldirs, to standardize things a bit,
though.

@icculus: You need to deal with the custom target stuff in CMakeLists.txt
(at the very least, `hg` use should go away, if not all of those..)

**Comment by icculus** [comment]
>  (at the very least, hg use should go away, if not all of those..)

This is gone now.

"make install" works here, and after, "make SDL2_sound-uninstall" works as well on Linux, etc (and is not meant to be used on anything but POSIX-like platforms, where a "make install" makes sense in the first place).

@jengelh If there's an error log or something, please post it, but CMake _should_ generate an "install" target for you.

**Comment by jengelh** [comment]
I had mixed up the directories; sorry for the noise. (%cmake in rpm makes a separate build directory)

**Comment by icculus** [comment]
No worries, I'm glad it's working now!
