### ISSUE TITLE
C++ compiler required but not exercised

### ISSUE THREAD

**Issue by jengelh** [icculus/SDL_sound#34]
SDL_sound 2.0.1's cmake scripts tests for a C++ compiler,

```
 CMake Error at CMakeLists.txt:7 (project):
   No CMAKE_CXX_COMPILER could be found.
```

but during build, this is never used as far as I can tell, as all source files are .c.

**Comment by sezero** [comment]
Does the following change help?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a2814e2..a4b64d3 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -4,7 +4,7 @@
 
 cmake_minimum_required(VERSION 2.8.12)
 
-project(SDL_sound)
+project(SDL_sound C)
 set(SDLSOUND_VERSION 2.0.1)
 
 # Increment this if/when we break backwards compatibility.
```

**Comment by sezero** [comment]
Tested myself that the change prevents cmake looking for a c++ compiler, so pushed as https://github.com/icculus/SDL_sound/commit/d31cee3bf4475eb424c19a22ebd03a2d4587c078
