### ISSUE TITLE
using add_subdirectory for SDL2 and SDL_sound is broken

### ISSUE THREAD

**Issue by ericoporto** [icculus/SDL_sound#40]
broken after: https://github.com/icculus/SDL_sound/commit/42c4f200c867cc7681b2e9b96057bb9e90355738

the problem: 
```
cmake_push_check_state()
set(CMAKE_REQUIRED_LIBRARIES ${SDL2_LIBRARIES})
check_function_exists(SDL_exp HAVE_SDL_EXP)
cmake_pop_check_state()
```

once we are in [check state](https://cmake.org/cmake/help/latest/module/CMakePushCheckState.html) we require SDL2_LIBRARIES, but they haven't been built yet - if both SDL2 and SDL_sound have been added using add_subdirectory, CMake will configure everything and then build everything.

If you are in a system with SDL2 libraries installed, this can be overlooked, as the check will happen with your system SDL2 and then following your project will build with the SDL2 you used add_subdirectory. 

I think add_subdirectory through CMake is a valid config (and it's used by a lot of SDL projects for adding their own dependencies, like SDL_image), and it's really useful for working in platforms that don't have package managers for C libraries like Android and consoles, and also for shipping games with SDL2 configured in a more sane way.

The error I get:

```
-- Looking for SDL_exp
CMake Error at build_13.2_debug/CMakeFiles/CMakeTmp/CMakeLists.txt:16 (add_executable):
  Target "cmTC_3bc0e" links to target "SDL2::SDL2" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

Alternative approaches:

- leverage pkgconfig to check old sdl2 version, and only act on knowing it's needed 
- figure a check for the symbol in `"SDL_stdinc.h"`, these could happen at config time. (maybe [`check_prototype_definition`](https://cmake.org/cmake/help/latest/module/CheckPrototypeDefinition.html)  ?)
- use a cmake option that skips this check (quick workaround, also very flexible!)

```
if(NOT SDLSOUND_HAVE_SDL_EXP)
cmake_push_check_state()
set(CMAKE_REQUIRED_LIBRARIES ${SDL2_LIBRARIES})
check_function_exists(SDL_exp SDLSOUND_HAVE_SDL_EXP)
cmake_pop_check_state()
endif()
```

**Comment by sezero** [comment]
The aforementioned patch is mine - don't know cmake thing enough to adapt and fix this one.

**Comment by icculus** [comment]
We're very likely going to add a hard dependency on SDL 2.0.10 soon (so we can use SDL_AudioStream for audio data conversion), which will make this SDL_exp check unnecessary.

I think until we do, it's probably reasonable to just link directly to libm on Linux systems, since it's always going to be available there anyhow and if we end up needing to call exp() directly, it'll work, and it's harmless otherwise.

**Comment by sezero** [comment]
> We're very likely going to add a hard dependency on SDL 2.0.10 soon (so we can use SDL_AudioStream for audio data conversion), which will make this SDL_exp check unnecessary.

That's good for SDL_exp. However, how to test that:
- Easy / lazy way: We can error out from SDL_sound_internal.h for SDL2 < 2.0.10
- Harder way: Cmake check: Only beginning with SDL2-2.0.12, we are installing a
  sdl2-config-version.cmake. Without it, cmake fails against an 2.0.10 installation
  like the following. Maybe requiring 2.0.12+ would be better if we want a cmake-time
  check.
```
CMake Error at CMakeLists.txt:30 (find_package):
  Could not find a configuration file for package "SDL2" that is compatible
  with requested version "2.0.10".

  The following configuration files were considered but not accepted:

    /home/sezero/testing/lib/cmake/SDL2/sdl2-config.cmake, version: unknown
```

**Comment by sezero** [comment]
> I think until we do, it's probably reasonable to just link directly to libm on Linux systems, since it's always going to be available there anyhow and if we end up needing to call exp() directly, it'll work, and it's harmless otherwise.

Pushed https://github.com/icculus/SDL_sound/commit/3ddd0e48da8513e8806c735615d6f12c2c45c640 - if it's good, we can close this.

**Comment by ericoporto** [comment]
> Pushed 3ddd0e4 - if it's good, we can close this.

It fixes for me! Feel free to close this!

**Comment by icculus** [comment]
> Easy / lazy way: We can error out from SDL_sound_internal.h for SDL2 < 2.0.10

That's exactly what we're going to do, but until we add the SDL_AudioStream stuff, this is resolved. Thank you!
