### ISSUE TITLE
Upsampling noise/crackling

### ISSUE THREAD

**Issue by higaski** [icculus/SDL_sound#46]
I've recently written a small application using SDL 2.0.20 and SDL_sound 2.0.1 hoping that this combination would handle resampling reasonably well. However I can't get it to work properly.

I'm opening a device with the following settings:
- AUDIO_S16LSB
- 1 channel
- 44100 Hz

Playing 44.1kHz samples with those settings works like a charm, however everything which needs upsampling (e.g. 11 or 22kHz) sounds horrible. There is a lot of noise and even occasional crackling. It almost sounds like there are samples missing (e.g. due to an off-by-one error or something).

It's definitively not a performance issue, I've even switched to decoding the whole sample upfront just to rule that out.

**Comment by higaski** [comment]
https://github.com/libsdl-org/SDL/issues/2663

**Comment by icculus** [comment]
As discussed in the SDL bug, the real problem here is likely the lack of SDL_AudioStream use...there's bug open about that: #38
