### ISSUE TITLE
ARM64 build failure with MSVC

### ISSUE THREAD

**Issue by sezero** [icculus/SDL_sound#58]
@ccawley2011 has recently reported an ARM64 build failure with MSVC at
https://github.com/mackron/dr_libs/issues/229

Is my suggested patch at https://github.com/mackron/dr_libs/issues/229#issuecomment-1084447914 correct for it?
If it is, apply here?

**Comment by icculus** [comment]
It looks correct to me.

**Comment by sezero** [comment]
Obviously causing build failures in linux and mac (see CI logs) - reopening.

**Comment by sezero** [comment]
Fixed by https://github.com/icculus/SDL_sound/commit/1b8c2fbc1184e61dcc5934313cc0a5363df63be2
