### ISSUE TITLE
playsound causes conflicts with existing SDL_sound packages

### ISSUE THREAD

**Issue by ccawley2011** [icculus/SDL_sound#63]
Both SDL_sound and SDL2_sound install the `playsound` application to the same location, which causes issues for package managers. The [FreeBSD package](https://www.freshports.org/audio/sdl2_sound) works around this by renaming it to `playsound2`.

**Comment by sezero** [comment]
Isn't the same true for other test programs of other SDL satellite projects, e.g. playmus of SDL_mixer? IMO, distros don't have to install the test programs.

**Comment by icculus** [comment]
Yeah, playsound wasn't meant to be a general media player utility one would install, but I can see people thinking that was the intention, and it _can_ be useful as a simple thing.

But I'd recommend they stop packaging SDL_sound 1.x as a better solution here.

**Comment by sezero** [comment]
I suggest closing this as not-a-bug.
