### ISSUE TITLE
MIDI playback on Windows is weird

### ISSUE THREAD

**Issue by ericoporto** [icculus/SDL_sound#68]
Test file: 
[prepare_your_swords.mid.zip](https://github.com/icculus/SDL_sound/files/8766585/prepare_your_swords.mid.zip)

I used playsound_simple itself to play the above MIDI on Windows. It doesn't sound right. I used the TIMIDITY sound fount from Nix:
[TIMIDITY.zip](https://github.com/icculus/SDL_sound/files/8766587/TIMIDITY.zip)

Is this working for others? I tested on VLC using the fluidsynth sound font from [here](http://www.schristiancollins.com/generaluser.php), and it sounded fine on it. On playsound_simple it sounds like something in the timing is wrong.

**Comment by ericoporto** [comment]
Nevermind, was using an old release.

**Comment by sezero** [comment]
Happens to all of us :)
