### ISSUE TITLE
Sound_GetDuration() backport to stable-1.0

### ISSUE THREAD

**Issue by SDLBugzilla** [icculus/SDL_sound#7]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Backport of Sound_DecodeAll() from development branch (sample_duration.patch, text/plain, 2012-04-22 16:47:38 +0000, 25310 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=848)

**Reported in version:** unspecified
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2012-04-22 16:47:38 +0000, Nikos Chantziaras wrote:

> Created attachment 848
> Backport of Sound_DecodeAll() from development branch
> 
> I was previously using SDL_sound for audio decoding in my apps and simply used Sound_DecodeAll() for the job.  That meant I could calculate the duration easily.  This was a horrible memory waster though (playing a few layered tracks simultaneously would eat up anywhere between 100 and 300MB RAM.)
> 
> So I switched to Sound_Decode().  However, being able to tell the duration of the sample is critical.  Since SDL_sound might need some time for a proper release, I ported Sound_DecodeAll() from the development branch to the stable-1.0 branch.  It's a backport of these:
> 
>   http://hg.icculus.org/icculus/SDL_sound/rev/c66080364dff
>   http://hg.icculus.org/icculus/SDL_sound/rev/3e705c9180e5
> 
> Note that binary compatibility with SDL_sound 1.0 is preserved.

**Comment by sezero** [comment]
IMO, we shouldn't add new apis to stable-1.0

**Comment by icculus** [comment]
> IMO, we shouldn't add new apis to stable-1.0

Agreed, this is just @SDLBugzilla pulling in all the old bugs from SDL's bug tracker, now that SDL_sound is on github. Closing this.
