### ISSUE TITLE
Can a new release be made?

### ISSUE THREAD

**Issue by ericoporto** [icculus/SDL_sound#83]
@madebr added really useful scripts in CMake to install a PKG config file, it would be super useful to have a new SDL Sound release after that has been added, as in theory I can now check for sdl sound installation dir using pkg config.

I mention pkg-config because we keep getting [issues](https://github.com/adventuregamestudio/ags/issues/2049#issue-1777655735) [about](https://github.com/adventuregamestudio/ags/issues/1442) [failure](https://github.com/adventuregamestudio/ags/issues/1941) to build ags because of sdl sound.

**Comment by icculus** [comment]
Sure, it's probably time for a 2.0.2 release. There are 60 commits since 2.0.1, so it's not a massive release, but there are some good fixes in there.

@sezero Anything we should squeeze in real fast?

**Comment by sezero** [comment]
Nothing, off the top of my head

**Comment by sezero** [comment]
Handling https://github.com/icculus/SDL_sound/issues/36 upon release would be nice though.

**Comment by icculus** [comment]
We are live! https://github.com/icculus/SDL_sound/releases/tag/v2.0.2

(Assuming I did this right to resolve #36.)

**Comment by ericoporto** [comment]
Yey! Amazing, thank you so much for this!
