### ISSUE TITLE
Emscripten: emcmake CMake fail, found relative path while evaluating include directories

### ISSUE THREAD

**Issue by ericoporto** [icculus/SDL_sound#84]
SDL_Sound no longer builds with Emscripten! It gives the following error now.

```
CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of
  "SDL2_sound-static":

    "_sdl2_include_dir-NOTFOUND"



CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "SDL2_sound":

    "_sdl2_include_dir-NOTFOUND"



CMake Error in CMakeLists.txt:
  Target "SDL2_sound" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "_sdl2_include_dir-NOTFOUND"


CMake Error in CMakeLists.txt:
  Target "SDL2_sound" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "_sdl2_include_dir-NOTFOUND"


-- Generating done
```

**To reproduce:**

1. Install emscripten emsdk

    git clone git clone https://github.com/emscripten-core/emsdk.git
    cd emsdk

Emscripten requires you have python 3 installed.

On bash:

    ./emsdk install 3.1.28
    ./emsdk activate 3.1.28
    source ./emsdk_env.sh

On cmd (no need to source):

    .\emsdk install 3.1.28
    .\emsdk activate 3.1.28

2. Build using cmake in emscripten

With emscripten activated, in the same terminal now switch to the directory where SDL_sound is cloned

    cd ../SDL_sound

And then just

    mkdir cmake-build-emscripten
    cd cmake-build-emscripten
    emcmake cmake ..

It should then start to configure and give the error right away!

**Comment by ericoporto** [comment]
I am not sure what is the issue so I will just comment some things. Let's look at [CMake docs](https://cmake.org/cmake/help/latest/command/get_target_property.html#get-target-property)

> Non-inherited properties will set `<VAR>` to `<VAR>-NOTFOUND`

So we have a bunch of 

    get_target_property(<VAR> target property)
    get_target_property(_sdl2_include_dir SDL2::SDL2-static INTERFACE_INCLUDE_DIRECTORIES)

This means the var `_sdl2_include_dir` is set to `_sdl2_include_dir-NOTFOUND` which is then interpreted later as a directory, and because it's not an absolute directory it fails and gives the error.

Now `SDL2::SDL2-static` doesn't exist in Emscripten which is built differently using a python script and generates a different CMake include script there just to shut up errors.

But we don't need to care for that, we may just check for `_sdl2_include_dir-NOTFOUND` and replace it by an empty string.

**Comment by ericoporto** [comment]
Emscripten simply sets a `SDL2_INCLUDE_DIRS` CMake variable with the directory, it's great because it's simple and it works. Can it just use that instead if this complex entrapment fails for the above case?

**Comment by icculus** [comment]
CC @madebr for insight on this.

I guess if nothing else, we could just check for Emscripten and force things appropriately, but I don't really understand this code enough to say what is going wrong here.

**Comment by madebr** [comment]
Let's use `SDL2_INCLUDE_DIRS` instead.
The real issue is emscripten not setting the `INTERFACE_INCLUDE_DIRECTORIES` property though.
(I've created https://github.com/emscripten-core/emscripten/pull/19780)

**Comment by ericoporto** [comment]
I don't need changes upstream there, I just want things to be fixed here. I can't depend forever on madebr fixing other toolchains to work with his complex ways, I would prefer to have ways to avoid all the generator expression stuff and simply use the variables that always worked. Let's make things simpler and not harder, reduction instead of addition.
