### ISSUE TITLE
Question: SDL_sound mixer

### ISSUE THREAD

**Issue by klei1984** [icculus/SDL_sound#87]
Hello,

 I accidentally bumped into a 15 years old fork of SDL_sound which had a built in software mixer API. Will it reappear in the future or would that API one way or another make its reappearance in SDL3_mixer?

Based on the old tutorial descriptions the API allowed sample manipulations and streaming which is what I am looking for. Or was the mixer API removed due to mojoAL maybe?

I am curious about what the future holds... thanks in advance.

**Comment by klei1984** [comment]
I will use miniaudio.

**Comment by icculus** [comment]
Yeah, it's not something I'm planning to work on any time soon, sorry.
