### ISSUE TITLE
Can't figure how to link independently of static/shared builds

### ISSUE THREAD

**Issue by ericoporto** [icculus/SDL_sound#89]
So, here's the thing, I want to link to `SDL2_sound::SDL2_sound` but have it be the static build, the reason being, if for some reason some wants to build SDL2_sound shared, they don't have to rename everywhere in the project where it's linked, essentially, I want to have one thing to link and then building SDL2_sound only statically it should work, or if for some reason SDL2_sound is built as a shared library it should work too. What is the approach to go here?

**Comment by icculus** [comment]
CC @madebr

**Comment by ericoporto** [comment]
My approach is to simply make an interface on my side in a check that the shared is off

```
  add_library(sdl2_sound-interface INTERFACE)
  target_link_libraries(sdl2_sound-interface INTERFACE SDL2_sound-static)
  add_library(SDL2_sound::SDL2_sound ALIAS sdl2_sound-interface)
```

I just have been deleting a little stuff on my side to rely more on the CMake stuff in SDL side and was curious if this was already covered here - I couldn't figure it out by reading the code.

**Comment by madebr** [comment]
#90 will ensure a `SDL2_sound::SDL2_sound` target.
This is the same behavior as SDL2, and the other satellite libraries.

If you can't include the patch immediately, use @ericoporto 's suggestion.
e.g.
```cmake
find_package(SDL2_sound REQUIRED)
if(NOT TARGET SDL2_sound::SDL2_sound)
  add_library(SDL2_sound::SDL2_sound INTERFACE)
  target_link_libraries(SDL2_sound::SDL2_sound INTERFACE SDL2_sound::SDL2_sound-static)
endif()
```

**Comment by ericoporto** [comment]
Thank you for the PR, works great! :)
