### ISSUE TITLE
AGS building warned for a lack of : SDL2_sound_INCLUDE_DIRS

### ISSUE THREAD

**Issue by Bug-Fighter** [icculus/SDL_sound#93]
Within Mageia 9 linux distribution, I built last stable SDL2_sound release. The rpm script build section was written as follow 

```
export CFLAGS="%{optflags} -lm"
%cmake -DSDLSOUND_BUILD_STATIC:BOOL=ON \
       -DSDLSOUND_BUILD_SHARED:BOOL=ON \
       -DSDLSOUND_DECODER_MIDI:BOOL=ON \
       -DSDLSOUND_DECODER_COREAUDIO:BOOL=ON
%cmake_build
```
RPM build and install worked fine.
Then, I used this new installed SDL2_sound package to build AGS (https://github.com/adventuregamestudio/ags). The rpm script build section was

```
export CFLAGS="%{optflags} -lm"
%cmake -DCMAKE_BUILD_TYPE=Release \
       -DAGS_USE_LOCAL_ALL_LIBRARIES:BOOL=ON \
       -DAGS_BUILD_ENGINE:BOOL=ON \
       -DAGS_BUILD_TOOLS:BOOL=OFF \
       -DAGS_BUILD_COMPILER:BOOL=OFF
%cmake_build
```
The build process (find_package(SDL2_sound REQUIRED)) warned for a lack of SDL2_sound includedir 

```
CMake Error at CMakeLists.txt:281 (include_directories):
  include_directories given empty-string as include directory.
```

Looking for a CMAKE_INSTALL_INCLUDEDIR value, I found an empty string.

I took a look to 'sdl2-config.cmake.in' and I patched 'cmake/SDL2_soundConfig.cmake.in' as follow 

```
--- cmake/SDL2_soundConfig.cmake.in	2023-06-29 16:48:42.000000000 +0200
+++ cmake/SDL2_soundConfig.cmake.in.diff	2024-01-17 20:29:09.651971920 +0100
@@ -20,4 +20,10 @@
     set(SDL2_sound_SDL2_sound-static_FOUND TRUE)
 endif()
 
+# AGS building warned for a lack of : SDL2_sound_INCLUDE_DIRS
+set_and_check(SDL2_sound_BINDIR         "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_BINDIR@")
+set_and_check(SDL2_sound_INCLUDE_DIR    "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@/SDL2")
+set_and_check(SDL2_sound_LIBDIR         "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@")
+set(SDL2_sound_INCLUDE_DIRS             "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@;@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@/SDL2")
+
 check_required_components(SDL2_sound)
```
And then, no more warning. AGS build worked fine.

As a conclusion, several questions arises:

- do I made a mistake when building SDL2_sound ?
- does AGS CmakeList doesn't read the correct value ?
- does the submitted patch pertinent ?

**Comment by ericoporto** [comment]
@Bug-Fighter , SDL_sound was never ever tested as local library in AGS.

The problem is all releases from this repository are broken for us. Whatever is the issue we report, it gets fixed really quick, but no new release is made.

Is there any reason you are not just building everything statically in the default configuration?

**Comment by Bug-Fighter** [comment]
I try to follow a private developing policy:

- choose stable releases to build required software
- use Red Hat package manager to manage dependencies, folders localization and version
- share a maximum amount of libraries 
- use a generator of build-systems, CMake, to move towards the goal of platform-independent project

However these are not mandatory criteria. I can go back to makefile as needed. I wholly know that no project can be fully tested. I made a try using my own way of working.  I give you a proposal, consider it as an humble contribution.

With my best thanks for your answer
Can be closed as is

**Comment by Bug-Fighter** [comment]
Your explanations are perfectly clear, my understanding a little bit less ...
I fully understand that continuous integration service can be expansive in many way.
Thanks again

**Comment by ericoporto** [comment]
@Bug-Fighter made a PR with the change, it's a very simple one, you can try it locally. It worked in my Ubuntu system, hopefully it works in your distro too!

**Comment by Bug-Fighter** [comment]
I downloaded SDL_sound-main.zip signed fdcecafbfdcbdd2b77c5b591948c237df19c864e
and ags-master.zip signed fba9544af4e652f831a43ff6557d35dd7538950a

rpmbuild did the job for both of them without any complain

then I played "Indiana Jones - The Temple of the Spheres" with the resulting ags with more fun then compute

You're sincerely thanked

**Comment by ericoporto** [comment]
This has been fixed (it was in ags and not here) and can be closed.
